export default {
    START_FETCH:'START_FETCH',
    SUCCESS_FETCH:'SUCCESS_FETCH',
    DEFEAT_FETCH:'DEFEAT_FETCH',
    CHANGE_STATE_START:'CHANGE_STATE_START',
    GET_PRODUCT_START:'GET_PRODUCT_START',
    GET_PRODUCT_SUCCESS:'GET_PRODUCT_SUCCESS',
    GET_PRODUCT_ERROR:'GET_PRODUCT_ERROR',
    ADD_TO_CART:'ADD_TO_CART',
    DELETE_FROM_CART:'DELETE_FROM_CART',
    REDUCE_PRODUCT:'REDUCE_PRODUCT'
}